### ISSUE TITLE
Feature Request: Ability To Rescrape Item

### ISSUE THREAD

**Issue by LoganWolverineX** [jurialmunkey/context.themoviedb.helper#1]
It would be a nice feature to be able to "Rescrape Item" for TMDb Helper widgets/shortcuts as well as for external addon widgets/shortcuts.  Hope that's doable.  Sometimes I don't want to  clear cache for the entire addon.

**Comment by jurialmunkey** [comment]
I don't know what you mean by "rescrape item". You can already Refresh Details from the context menu on TMDbHelper items.

**Comment by LoganWolverineX** [comment]
After an addon searches for links, it is cached for a certain amount of hours so it loads the page faster. “Rescrape item” allows the user clear the cache of links searched. One can just clear the cache for the addon, but the benefit of this option is that it only clears the cache of link results for that one particular episode or movie.

**Comment by jurialmunkey** [comment]
I can't refresh some other addon's cache...

**Comment by jurialmunkey** [comment]
The addon in question needs to expose a plugin endpoint that allows for refreshing the cache. In which case you then need to deal with this by having a player which calls the correct plugin path to refresh that addon's cache before scraping. Absolutely nothing to do with TMDbHelper.

**Comment by LoganWolverineX** [comment]
Gotcha. Thanks for the explanation. Appreciate it.
