### ISSUE TITLE
[Enhancement] Add options to view Reviews, Trivia and Parental Guide in the context menu

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/context.themoviedb.helper#4]
Hi @jurialmunkey,

Could you please add options in the context menu to view Reviews, Trivia and Parental Guide?

One of the video addons already implemented this feature some time back. See screenshots below. So it will be really useful if TMDB Helper also have these features by default.

![IMG20220628092342](https://user-images.githubusercontent.com/65297828/176088880-db0c100e-a819-403f-be36-e1a7e8bed0f1.jpg)

![IMG20220628092352](https://user-images.githubusercontent.com/65297828/176088909-e0f3d8de-9a8f-476d-81a4-8fde9f493e22.jpg)

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
Where is this data coming from? Looks like Web page scraping stealing copyrighted data that is not available for use in other apps without paying a license fee.

**Comment by AakashC2020** [comment]
> Where is this data coming from? Looks like Web page scraping stealing copyrighted data that is not available for use in other apps without paying a license fee.

Hi @jurialmunkey,

Oh okay, I had no idea about that. I think the data is coming from IMDB website. Sorry about this request then! You can ignore this. Thanks for your feedback!

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment]
imdb data is copyrighted and not open source. Their api is not free and requires a license fee to use. Scraping their website to take this data for non-personal use (eg such as in an external app) is not permitted by their terms of use. 

I definitely don't want a lawsuit from Amazon (who own imdb) so safe to say I won't be doing anything of the sort.

**Comment by AakashC2020** [comment]
> imdb data is copyrighted and not open source. Their api is not free and requires a license fee to use. Scraping their website to take this data for non-personal use (eg such as in an external app) is not permitted by their terms of use.
> 
> I definitely don't want a lawsuit from Amazon (who own imdb) so safe to say I won't be doing anything of the sort.

Hi @jurialmunkey,

Neither I was aware of the copyright issues, nor I was sure whether the data is coming from IMDB. I just thought that the features looked useful hence I requested. I really apologize for making this request without researching more. The TMDB Helper addon and the Arctic Horizon 2 skin are already great without these features. Thanks for all your hard work!

Thanks and Regards,
ShibajiCh.
